### ISSUE TITLE
Axiomatise catalytic activities

### ISSUE THREAD

**Issue by dosumis** [geneontology/molecular_function_refactoring#22]
Editors recently agreed agreed a strategy for axiomatising catalytic activities in GO by pulling information from Rhea. 

Details of discussion can be found here:
http://wiki.geneontology.org/index.php/Ontology_meeting_2016-09-29#RHEA_update_request

Summary of strategy:

1. Record only necessary conditions* and encode directionality reflecting how these reactions are conventionally drawn and their predominant direction under physiological conditions.
     e.g. Translate the reaction   X + Y -> A + B  into 
      SubClassOf has_input some X
      SubClassOf has_input some Y
      SubClassOf has_output some A
      SubClassOf has_output some B

2. Add a standard comment to all terms explaining the design decision.

3. Extract classification from EC wherever possible.  We can do this for Rhea reactions wherever they have a mapping to an EC, or an EC used as a classification.

4. Explore full logical definition for some branches (e.g. transporters).

* Note that it is not safe to add full logical definitions without the ability to record cardinality and to add closure axioms. This would be safe, but is outside EL and so has scaling problems:

X + Y -> A + B
=>
EquivalentTo: 
(has_input exactly 1 X) and (has_input exactly 1 Y) and has_input only (X or Y) 
and
(has_output exactly 1 A) and (has_output exactly 1 B) and has_output only (A or B)

It may be worth automatically generating this and testing reasoning with it as a separate module.

**Comment by dosumis** [comment]
In discussion with Paul T: he was skeptical that stochiometry would matter, but that still leaves closure axioms.

**Comment by cmungall** [comment]
Did you discuss directionality?

**Comment by dosumis** [comment]
Paul happy with the strategy described above including adding direction & deriving classification from EC where possible.

**Comment by dosumis** [comment]
@cmungall  - any idea of a timescale for this?  Did you make a start?

Asking as wondering whether worth adding a few key ones by hand.

**Comment by cmungall** [comment]
Partially related: EC xref analysis here: https://github.com/geneontology/go-xref-analysis

**Comment by ukemi** [comment]
We need to be careful that the EC definitions are bidirectional and in most cases, that is what we have used in GO. In the pathways work, we made has-part relationships between glycolytic enzymes and the pathway for the enzymes that run in both directions. PMID:27589964.

**Comment by cmungall** [comment]
2667 of the RHEA xrefs are to BI

Here is en exhaustive list of non-BI xrefs. Is there any rationale for this, or is it arbitrary?

```
LR      RHEA:10377 ! ATP + Cu(2+)(in) + H2O => ADP + Cu(2+)(out) + H(+) + phosphate     GO:0004008 ! copper-exporting ATPase activity
LR      RHEA:29900 ! D-xylose(out) + ATP + H2O => D-xylose(in) + ADP + H(+) + phosphate GO:0015407 ! monosaccharide-transporting ATPase activity
LR      RHEA:14614 ! ATP + H2O + taurine(out) => ADP + H(+) + phosphate + taurine(in)   GO:0015411 ! taurine-transporting ATPase activity
LR      RHEA:21669 ! sn-glycerol 3-phosphate(out) + ATP + H2O => sn-glycerol 3-phosphate(in) + ADP + H(+) + phosphate   GO:0015430 ! glycerol-3-phosphate-transporting ATPase activity
RL      RHEA:14031 ! AH2 + selenate => A + H2O + selenite       GO:0033797 ! selenate reductase activity
RL      RHEA:19995 ! [thioredoxin]-dithiol + L-methionine (S)-S-oxide => [thioredoxin]-disulfide + L-methionine + H2O   GO:0036456 ! L-methionine-(S)-S-oxide reductase activity
RL      RHEA:26456 ! acryloyl-CoA + H(+) + NADPH => NADP(+) + propanoyl-CoA     GO:0043957 ! acryloyl-CoA reductase (NADP+) activity
LR      RHEA:25075 ! (9Z,11E,13S,15Z)-13-hydroperoxyoctadeca-9,11,15-trienoate => (9Z,13S,15Z)-12,13-epoxyoctadeca-9,11,15-trienoate + H2O      GO:0047987 ! hydroperoxide dehydratase activity
LR      RHEA:21881 ! 2 H(+) + O2 + oxalate => 2 CO2 + H2O2      GO:0050162 ! oxalate oxidase activity
LR      RHEA:14526 ! beta-cyclopiazonate + A => alpha-cyclopiazonate + AH2      GO:0050448 ! beta-cyclopiazonate dehydrogenase activity
RL      RHEA:25651 ! (6R)-isoperitenone + H(+) + NADPH => (2R,5R)-isopulegone + NADP(+) GO:0052581 ! (-)-isopiperitenone reductase activity
LR      RHEA:25322 ! N-methylethanolamine phosphate + S-adenosyl-L-methionine => N,N-dimethylethanolamine phosphate + S-adenosyl-L-homocysteine + H(+)       GO:0052667 ! phosphomethylethanolamine N-methyltransferase activity
LR      RHEA:26435 ! L-serine + indole => L-tryptophan + H2O    GO:0052684 ! L-serine hydro-lyase (adding indole, L-tryptophan-forming) activity
LR      RHEA:21253 ! (S)-2-hydroxyglutarate + A => 2-oxoglutarate + AH2 GO:0061758 ! 2-hydroxyglutarate dehydrogenase activity, forward reaction
LR      RHEA:33200 ! butanal + H(+) + NADH => butan-1-ol + NAD(+)       GO:1990362 ! butanol dehydrogenase activity
```


here is a random BI:

```
BI      RHEA:11031 ! D-mannose + ATP <=> D-mannose 6-phosphate + ADP + H(+)     GO:0019158 ! mannokinase activity
```

If we do commit to directionality, we will need to map down the BIs to the appropriate direction.

**Comment by ukemi** [comment]
If I recall correctly the non-bidirectional mappings were done by Jane (?) and they really reflected unidirectionality in biological systems. I think these were done as examples.

**Comment by ukemi** [comment]
For example, see how some are called 'forward reaction' or 'exporter'.

**Comment by ukemi** [comment]
Also note the definitions have a => and not a =.

**Comment by pgaudet** [comment]
This can be closed as we are creating definitions and xrefs to Rhea in this project:
https://github.com/geneontology/go-ontology/projects/10
