### ISSUE TITLE
Proposal for recording MF specificity in GO

### ISSUE THREAD

**Issue by dosumis** [geneontology/molecular_function_refactoring#24]
We don't represent MF specificity well at all in GO. In some cases, this is critical to properly capturing function.  An obvious example is ion channel selectivity. Knowing ion specificity critical to understanding the physiological role of a channel.

With OWL-DL expressiveness, this would be reasonably straightforward:

chloride specific ion channel: EquivalentTo ion channel that (transports some chloride) and (transports only chloride)*

In the absence, we may be able to can the PATO shunt pattern.

chloride specific ion channel: Equivalent to 'ion channel that (transports some chloride ion) and (bearer_of some 'chloride specificity')

PATO: single inorganic ion specificity
.   PATO: 'chloride specificity'
.   PATO: 'potassium specificity'

GCI: bearer of some 'chloride specificity' EquivalentTo (transports some chloride) and ('transports only chloride)  # Annotate this as DL only.

Programmatically roll pairwise disjointness axiom for all (direct) subclasses of 'single inorganic ion specificity':

DisjointClasses: ('bearer of' some 'chloride specificity'),('bearer of' some 'potassium selectivity')

* This is probably more restrictive than is realistic.  Often low conductance of other ions + conductance of non-physiologically relevant related ions - but probably safe to gloss.

CC @cmungall @thomaspd

**Comment by pgaudet** [comment]
This seems an annotation issue rather than ontology.
