### ISSUE TITLE
Decide on new upper level classification in MF

### ISSUE THREAD

**Issue by dosumis** [geneontology/molecular_function_refactoring#27]
@thomaspd suggestion (from [webProtege model](https://webprotege.stanford.edu/#Edit:projectId=ea132f81-760a-43f2-b5a9-fbe763bb7eed))

molecular_mechanism: "The physico-chemical process by which a molecular component function is carried out.  Note that while all molecular component functions must be carried out by one or more molecular mechanisms, it is possible that a molecular mechanism may not necessarily result in a molecular component function.  For example, a gene product might bind another molecule but have no functional effect on that other molecule."

![image](https://cloud.githubusercontent.com/assets/112839/22682888/4b4e232e-ed0d-11e6-867b-b598121914ee.png)

molecular component function : "The function that a molecule carries out, by virtue of direct molecular interactions, as a component of larger biological systems.  Molecular component functions must be carried out by a physical 'molecular mechanism' class."

![image](https://cloud.githubusercontent.com/assets/112839/22663212/b14fae64-eca3-11e6-8458-30ed72353581.png)

![image](https://cloud.githubusercontent.com/assets/112839/22682916/69c39a6e-ed0d-11e6-9933-b7c8c17a5543.png)

**Comment by dosumis** [comment]
Notes:

'Mechanism' includes only simple molecular functions.  What about the mechanisms of compound functions (e.g. receptors, TFs)?

molecular component function mixes MFs that can be defined by the very narrow context of direct interactions (e.g. receptor activity) and terms which can only be defined in a much wider biological process context (e.g. chemoattractant activity).   The former sound much more like 'mechanisms'.

**Comment by dosumis** [comment]
Paul on criteria for defining MF vs BP:

MF is process carried out by a single GP or complex.  BP is a causally-linked network of such processes. 

1. General classes of processes carried out by a single GP are MFs not BPs (topiosomerase activity is_a DNA tertiary structure modifying activity).  
1. MFs may be simple or compound - made up of simple (indivisible) MFs. These are often 
   * causally linked e.g. ligand binding regulates effector function in a receptor
   * link by energy transfer (ATPase provides energy for ion transporter)
1. MFs may also be single steps in the context of a larger process:  cell adhesion mediator activity (single step is binding; context is cell adhesion); chemoattractant activity (single step is binding and activating signaling receptor; context is chemotaxis).

simple function
compound function
molecular component function / contextual function <- Use this for \#3. 

simple and compound function are disjoint.

**Comment by dosumis** [comment]
Paul's suggested names:

 - [x] simple function AKA mechanism -> biochemical activity (ADDED IN BRANCH)
 - [x] molecular component function  -> system component function (ADDED IN BRANCH)

**Comment by pgaudet** [comment]
This proposal was not implemented. See how top level classes were fixed here: 
https://github.com/geneontology/go-ontology/issues/14266
