### ISSUE TITLE
cell adhesion mediator

### ISSUE THREAD

**Issue by dosumis** [geneontology/molecular_function_refactoring#28]
[For more details see refactoring proposal in WebProtege](https://webprotege.stanford.edu/#Edit:projectId=ea132f81-760a-43f2-b5a9-fbe763bb7eed)

### Proposed class: 
cell adhesion mediator

### Proposed text def: 

"Interacting selectively and non-covalently with any protein or
protein complex contributing to the adhesion of two different types of
cells."

DOS notes: 

1. This is defined for cell-cell adhesion rather than just
cell-adhestion (which cover adhesion to matrix too).
2. Could be more tightly defined as the binding event that
mediates cell-adhesion (or cell-cell adhesion, depending on event).

### Usefulness for biologists:

*Does this provide a useful grouping of molecular functions that cannot
 equally be provided by an existing biological process?  if so please
 describe*

Cell adhesion molecule is a very common and useful grouping of gene
product by function.  This class is intended to reflect this and so is
undoubtedly useful.  

Potential redundancy with BP:  cell-adhesion, cell-cell adhesion etc
are slightly broader.

We already have: 
'protein binding involved in cell adhesion' GO:0098631 
EquivalentTo 'protein binding' and ('part of' some 'cell adhesion')

#### Is this class useful for curators  - e.g. used in templates or
     guiding template usage?

It probably makes sense to generate a template for these.

#### Does this class require multiple inheritance classification?

Dual classification under binding.

*If yes please provide details/examples.*

#### Can we use design patterns & reasoning to populate subclasses?

*If yes, please provide details*

Challenge - we can easily specify involvement in cell-cell adhesion - but how do we specify that binding between adhesion molecules mediates cell-cell adhesion.

Experimental lego model for a classical cell-adhesion molecule:

![image](https://cloud.githubusercontent.com/assets/112839/22739833/499a54e6-ee05-11e6-9f15-1fc7fdb511a7.png)

(Not intended as a standard LEGO model - more as an illustration of the biology)

There are a couple of issues here:

1. How to represented binding when both inputs are gene products.
2. Location in this model is recorded via part_of.  This fits with
classical annotation, but not with standard LEGO annotation.  For that
we would use occurs_in - but this is not strictly true.  The gene
products are located in the PM, but binding does not happen there
(unless we extend the concept of what counts as plasma membrane to the point where the two cells involved spatially overlap).

Class level pattern sketch (treating as compound function):

cell adhesion mediator activity
part_of some cell-cell adhesion
has_part some (binding and has_input some (capable_of cell-cell adhesion mediator activity))  <-- could maybe use SELF here?

But this is not sufficient as it would cover dimerization between cells.

**Comment by thomaspd** [comment]
could the definition include protein anchor (GO:0043495) that part_of some cell adhesion process

**Comment by dosumis** [comment]
May be best to admit defeat on the class level and just add necessary conditions.  But it is still worth making a graph-like template for the instance level.  The one remaining issue for that is part_of vs occurs in - the GPs are part of the PM but the process occurs extracellularly.

**Comment by pgaudet** [comment]
Logical definition is now 

binding and ('part of' some 'cell adhesion')
