### ISSUE TITLE
Intercellular signal

### ISSUE THREAD

**Issue by dosumis** [geneontology/molecular_function_refactoring#30]
[For more details see refactoring proposal in WebProtege](https://webprotege.stanford.edu/#Edit:projectId=ea132f81-760a-43f2-b5a9-fbe763bb7eed)

### Proposed class: 

intercellular signal (activity)

### Proposed text def: 

A molecule produced by one cell, that interacts with a receptor on another cell.  The molecule generally diffuses from one cell to another, though some types of signal molecules (such as Notch ligands) are attached to the cell surface.

### Proposed classification(s) / example subclasses

Subclasses:

![image](https://cloud.githubusercontent.com/assets/112839/22741140/0fb98184-ee0a-11e6-9de7-272f6911950e.png)

Note - note all morphogens fit here:  bicoid is not a ligand (its a homoedomain-containing TF) and it doesn't diffuse between cells but between nuclei in a syncytium.  Some other subclasses (e.g. chemoattractant) can be defined with an additional differentium referencing a process.

### Usefulness for biologists:

*Does this provide a useful grouping of molecular functions that cannot
 equally be provided by an existing biological process?  if so please
 describe*

This is potentially useful for classifying ligands.  But note, we
already have:

"receptor agonist activity" (GO:0048018)
definition "Interacts with receptors such that the proportion of receptors in the active form is increased."^^xsd:string
has\_broad_synonym "receptor ligand activity"
SubClassOf:
	'part of' some 'signal transduction'*
	'receptor activator activity'  -> signaling receptor activator activity
	'receptor binding'

* signal transduction part_of cell-cell signaling which includes
  release of signal etc.
  
  This seems to cover what's needed.  The intercellular
  bit is implicit (via cell-cell signaling parentage).

#### Does this class require multiple inheritance classification?

*If yes please provide details/examples.*

Dual parentage with binding.  May be able to deal with this manually?

#### Can we use design patterns & reasoning to populate subclasses?

*If yes, please provide details*

This may not quite be sufficient:

'receptor binding' that directly_positively_regulates some 'signaling receptor activity'

(see example of receptors whose activity is additionally positively regulated by intracellular ATP or ion concentration.  Also NMDA glutamate receptor response to glycine.

**Comment by dosumis** [comment]
Proposed solution:

![image](https://cloud.githubusercontent.com/assets/112839/22784200/114d6728-eec7-11e6-8d56-b50d047a61bc.png)

To be resolved: relationship to "receptor agonist activity" (GO:0048018)- superclass or merge?

**Comment by pgaudet** [comment]
Was dealt with by renaming 'receptor agnonist activity' -> 'receptor ligand activity' and fixing children.
