### ISSUE TITLE
molecular energy harvesting

### ISSUE THREAD

**Issue by dosumis** [geneontology/molecular_function_refactoring#32]
[For more details see refactoring proposal in WebProtege](https://webprotege.stanford.edu/#Edit:projectId=ea132f81-760a-43f2-b5a9-fbe763bb7eed)

### Proposed class: 

molecular energy harvesting

### Proposed text def:  

"The use of an energy source (\"chemical potential\"), which will be coupled to another molecular function that requires energy."

### Proposed classification(s):

![image](https://cloud.githubusercontent.com/assets/112839/22790240/6f1c6514-eedd-11e6-8ac0-665276b9f432.png)

### Usefulness for biologists:

*Does this provide a useful grouping of molecular functions that cannot
 equally be provided by an existing biological process?  if so please
 describe*

#### Does this class require multiple inheritance classification?

*If yes please provide details/examples.*

#### Can we use design patterns & reasoning to populate subclasses?

*If yes, please provide details*

**Comment by dosumis** [comment]
If we only have ATPase under here, it may not be worth having *BUT* ATPase, coupled is a compound function.  Moreover this a special case of a compound function where one function is to produce energy to drive the other.  Other examples include:
 ATP synthase; 
electron transport chains;
antiporters and symporters where movement of one ion down a concentration gradient drives pumping of another up a concentration gradient;
photon absorption in photosystems I and II in photosynthesis.

By analogy with molecular transducer, we could model this on the instance level with a relation linking energy provider to energy using MF (provides_energy_for?).  On the class level we *could* have specific subpropertie of has_part/component by analogy with transducers.  But there may not be enough complexity in ontology to justify this.

**Comment by pgaudet** [comment]
Right now this is the structure: 


- 'molecular transducer activity'
-- 'energy transducer activity'
--- 'light transducer activity'

@thomaspd is this what you wanted ?

**Comment by pgaudet** [comment]
@thomaspd I think we decided NOT to create the branch 'molecular mechanism' - since in the end the mechanisms were binding and catalysis. 

I am closing; @thomaspd please reopen if needed. 

Pascale
