### ISSUE TITLE
DNA structure modifier (activity)

### ISSUE THREAD

**Issue by dosumis** [geneontology/molecular_function_refactoring#33]
### Proposed class: 

DNA structure modifier

### Proposed text def:  

"Through direct physical interaction, modifies the structure of a DNA molecule.  This modification can be to the primary structure (e.g. through nuclease activity or base-modifying enzymes), secondary structure (e.g. strand separation) or tertiary structure (e.g. DNA bending)."

### Proposed classification(s) / example subclasses

This bundles together modifiers of primary, secondary and tertiary
structure.  Name may not be clear enough to get this across.   

"molecular function acting on DNA" wouldn't work because transcription factors & RNA polymerase act on DNA but don't modify it.

##### Notes on potential subclasses:

* Sequence-specific vs nonspecific
* Covalent vs binding
* Primary (covalent), secondary (base-pairing, strandedness), tertiary structure (e.g. bending)
* Primary: distinguish between sequence (backbone) modifying vs base modifying while backbone linked

DNA structure covalent modfier activity
equivalentTo catalytic activity has_input some DNA
[For more details see refactoring proposal in WebProtege](https://webprotege.stanford.edu/#Edit:projectId=ea132f81-760a-43f2-b5a9-fbe763bb7eed)

DNA secondary structure modifier activity - changed strand number

DNA tertiary structure modifier activity - changes the shape (bending,
winding)

### Usefulness for biologists:

*Does this provide a useful grouping of molecular functions that cannot
 equally be provided by an existing biological process?  if so please
 describe*

Seems like a very general class.  Immediate children might be more useful.  Also might be surprising to users to find synthesis and catabolism under here.

#### Does this class require multiple inheritance classification?

*If yes please provide details/examples.*

Yes.  parallel to EC classification.

#### Can we use design patterns & reasoning to populate subclasses?

*If yes, please provide details*

Not obvious.  has_participant some DNA is too broad (see Transcription factor etc).

**Comment by dosumis** [comment]
- [ ] TODO work on subclass definitions with @phillord

**Comment by pgaudet** [comment]
redundant with https://github.com/geneontology/go-ontology/issues/16804
