### ISSUE TITLE
move and rename 'binding, bridging'

### ISSUE THREAD

**Issue by dosumis** [geneontology/molecular_function_refactoring#34]
This is a compound function - it binds more than one macromolecules (possible edge case - binding to polar head group of a phospholipid).

- [ ] Move under whatever 'molecular component function' ends up being called.
- [ ] Rename -> (macro)molecular adaptor (activity)

(Becomes a structural molecule via part_of some organization)

**Comment by pgaudet** [comment]
Fixed in the MF factor work with @thomaspd
