### ISSUE TITLE
small molecule interconversion

### ISSUE THREAD

**Issue by dosumis** [geneontology/molecular_function_refactoring#35]
Intention is to distinguish catalytic processes acting on an 'information biomacromolecule' (CHEBI:33695) from those acting on other molecules.  We can't do this logically with the way ChEBI is built (we don't have a class representing the complement of 'information biomacromolecule' (CHEBI:33695).  But we could derive a small molecule list using a closed world intepretation of ChEBI (e.g. via graph reasoning).  @cmungall - Can you script adding a derived class like this to GOCHE?

**Comment by ValWood** [comment]
Super!

(The small-molecule  metabolism list is really useful for metabolic modellers etc)

**Comment by pgaudet** [comment]
This issue was moved to geneontology/go-ontology#16974
