### ISSUE TITLE
structural molecule (activity)

### ISSUE THREAD

**Issue by dosumis** [geneontology/molecular_function_refactoring#36]
[For more details see refactoring proposal in WebProtege](https://webprotege.stanford.edu/#Edit:projectId=ea132f81-760a-43f2-b5a9-fbe763bb7eed)

### Proposed class: 
structural molecule

### Proposed text def: 

The action of a molecule that contributes to the structural integrity of a complex or assembly within or outside a cell.

### Usefulness for biolgists:

*Does this provide a useful grouping of molecular functions that cannot
 equally be provided by an existing biological process?  if so please
 describe*

#### Does this class require multiple inheritance classification?

*If yes please provide details/examples.*

#### Can we use design patterns & reasoning to populate subclasses?

*If yes, please provide details*

EquivalentTo:
'macromolecular adaptor'* that part_of some 'cellular component organization'

**Comment by pgaudet** [comment]
Term unchanged in the 2018 MF refactoring.
