### ISSUE TITLE
general classification of receptor activity

### ISSUE THREAD

**Issue by dosumis** [geneontology/molecular_function_refactoring#38]
### What we currently have

![image](https://cloud.githubusercontent.com/assets/112839/23067008/34970316-f515-11e6-8291-f0609ac9201c.png)

Question 1:  Should we have a general receptor term that groups cargo receptors and receptors that transduce some signal across the membrane receptors?  This is almost certainly too challenging to define formally.

Question 2: Should we have a class that covers photoreceptors and receptors that bind ligands?
A:  Yes. Most photoreceptors are GPCRs.   It would be v.odd if only some GPCRs classified under receptor.

###  Differentia

* Activated by binding of ligand or by sensing some other stimulus (see photoreceptor)
  Potential naming: ligand binding receptor vs ???

* Location of activity
   * intracellular (nuclear receptors; IP3 receptors on the ER) 
       suggested name: intracellular receptor
       suggested differentium:  occurs_in some intracellular
   * receptor in plasma membrane 
   * transmembrane (transduces signal across membrane)
         name: transmembrane receptor
         def: Stimulation of a sensor activity on one side of the membrane regulates an effector function on the other side of the membrane. 
      differentium:  occurs_in some membrane - doesn't quite work.  Can we explicitly encode that it transduces a signal across a membrane?  Or that the gene product 

* source of stimulus (would be nice to hook this up to response to stimulus, but that whole branch of the ontology needs a lot of work.
   *  intracellular  (e.g. IP3 receptor; ryanodine receptor). Term only used for transmembrane transducers.  We wouldn't call calmodulin a Ca2+ receptor, or PKC a DAG receptor.
   name: receptor activity responding to intracellular ligand
   def: receptor activity in which the signaling 
   occurs_in some intracellular
   differentium for TM receptor
   part_of cellular response to intracellular stimulus  <- TBA - needs work.
   *  extracellular  
      (no grouping class needed?)    
       * environmental
           name: environmental sensing
          * sensory (odorant receptors, taste receptors, photoreceptors)
             part_of some sensory perception
       * cell cell signaling
          name: cell-cell signaling receptor activity
          differentium: part_of signal reception involved in cell-cell signaling
       *  ECM - cell signaling
      name: cell-ecm signaling receptor activity

**Comment by dosumis** [comment]
Draft classification: 

![image](https://cloud.githubusercontent.com/assets/112839/23072016/22e54976-f528-11e6-89b7-629a89843ebc.png)

**Comment by dosumis** [comment]
Terminological issues:

Terminology problems & scale.

signal, transducer, transduction - information transfer operating at
various scales; within a protein; along a regulatory chain within a
cell; between cells.  This can start within a cell, within the
extracellular environment or ECM, from another cell, trom the
environment.

When we use these terms in BP, we mean information on a scale larger
than a protein.  If we use BP as a differentium for MF the scales
clash.

A molecular transducer transduces what?  A signal?  But signal on the
BP scale is most likely to mean an endogenous signal within the cell, from another cell or perhaps
from the ECM.  This excludes stimuli with environmental origins.

**Comment by dosumis** [comment]
Terminology problems & scale.

signal, transducer, transduction - all these terms are used to refer to information transfer operating at various scales; within a protein; along a regulatory chain within a cell; between cells; between a cell's environment and a cell. 

The use of terminology on these various scales poses a challenge for term naming.  Should the term 'signal' be reserved for receptors detecting endogenous ligands, should it be restricted to those used in cell-cell signaling, or should it refer to all transducing receptors.  Should we reserve the term 'signal transducer' for components of a signal transduction pathway?

In the end, no terminology is going to be entirely unambiguous.  Clarifying comments will inevitably be needed.

**Comment by thomaspd** [comment]
Something like this might work:

Regulated activity (sensing activity internally regulates some molecular function)
	-Transducer activity (sensing activity internally regulates some molecular regulator activity)
		--Receptor activity [(sensing activity occurs in location 1) internally regulates (molecular regulator activity occurs in location 2)]

Location 1 and 2 are disjoint.

This would classify any transmembrane transducer as a receptor, which I think is accurate.  Note that transducer has a regulatory activity as the effector, this was my original definition.  Signal transducer would then be a further subclass, as you suggest.

**Comment by pgaudet** [comment]
Signaling receptor and cargo receptor we split in the new MF. 

See - among other tickets: https://github.com/geneontology/go-ontology/issues/15234
