### ISSUE TITLE
Make design pattern and template for GPCR activity

### ISSUE THREAD

**Issue by dosumis** [geneontology/molecular_function_refactoring#41]

**Comment by thomaspd** [comment]
A start:

has_part sensing activity occurs in extracellular space near plasma membrane
directly (internally) activates
has_part (GEF activity has_input some target-protein) occurs in cytosol near plasma membrane

See LEGO Model: http://noctua.berkeleybop.org/editor/graph/gomodel:580685bd00000200

**Comment by pgaudet** [comment]
GPCRs can be elsewhere than PM (for eg in ER), so this proposal cannot be implemented.
