### ISSUE TITLE
Formal def for GEF activity

### ISSUE THREAD

**Issue by dosumis** [geneontology/molecular_function_refactoring#44]
Define this as a compound function encompassing binding and exchange?

CC @thomaspd - comments please.

**Comment by thomaspd** [comment]
I'd suggest that it is a protein binding that (directly inhibits (GDP binding enabled by binding-partner) and directly activates (GTP binding enabled by binding-partner)).

This way it should be automatically classified under "molecular function regulator via binding", which should be something like:
is a binding that directly regulates some (molecular function enabled by binding-partner)

**Comment by dosumis** [comment]
I think that works.  

'protein binding' that directly_negatively_regulates some 'GDP binding' 

This may not be necessary and sufficient though.  For a start, the target needs to be a GTPase.

In LEGO:
                                                                     __enables -> GTPase activity 
                                                                    |
GEF -enables-> binding -> has_input -> X -enables-> GDP binding
.                              |______directly_negatively_regulates____^


We may not need necessary and sufficient here though, if number of subclasses of GEF activity likely to be small.

**Comment by dosumis** [comment]
Possible ways to make the definition necessary and sufficient:

* Would it be true to say that by removing the GDP it directly_positively_regulates GTPase activity?
 (even if there is a lag)?
* add BP context: part_of some 'signal transduction' (?)

**Comment by thomaspd** [comment]
Note in my original definition above that the GEF activity has two effects:
directly inhibits (GDP binding enabled-by G-protein)
directly activates (GTP binding enabled-by G-protein)

The GEF activity does not affect the GTPase activity of the G-protein.  GAP activity activates the GTPase activity of the G-protein.  It's probably helpful to explain the pattern I'm assuming for the overall "G-protein activity" (not currently in GO, but should be):
G-protein activity:
has_part molecular function regulator via binding
has_part GDP binding
has_part GTP binding internally activates some (molecular function regulator activity via binding)
has_part GTPase activity (internally activates GDP binding AND internally inhibits GTP binding)

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/23289708/8b917240-fa43-11e6-9e7b-384eea4cb99a.png)

![image](https://cloud.githubusercontent.com/assets/112839/23289840/57f0640e-fa44-11e6-8036-00607a986b6c.png)


Re-using 'small GTPase binding' classes defined with ref to PRO:
![image](https://cloud.githubusercontent.com/assets/112839/23289563/7e011744-fa42-11e6-9e8b-16273b917b52.png)

![image](https://cloud.githubusercontent.com/assets/112839/23289802/2cba282e-fa44-11e6-89b0-5e16fe469aac.png)


Used directly_positively_regulated_by rather than has_sensor pattern here.  These should be equivalent (although are not formally yet).  Using the complete transducer pattern (has sensor cAMP binding, has effector GEF) would move the class out of the GEF hierarchy.

**Comment by pgaudet** [comment]
Implemented as described above.
