### ISSUE TITLE
Specific molecular function regulator 

### ISSUE THREAD

**Issue by dosumis** [geneontology/molecular_function_refactoring#46]
[For more details see refactoring proposal in WebProtege](https://webprotege.stanford.edu/#Edit:projectId=ea132f81-760a-43f2-b5a9-fbe763bb7eed)

### Proposed class: 

Specific molecular function regulator 

### Proposed text def: 

A gene product that controls the molecular function of another gene product, by modulating the functional efficiency of each target molecule.

*Notes: 

* Does this include indirect as well as direct?
  If direct then is this equivalent to GO:molecular function regulator activity ?
* What does 'modulating functional efficiency' mean?

### Proposed classification(s):

system component function

### Example subclasses:

![image](https://cloud.githubusercontent.com/assets/112839/23116678/b3f4b132-f743-11e6-9684-0ce021bd34fb.png)

### Usefulness for biolgists:

*Does this provide a useful grouping of molecular functions that cannot
 equally be provided by an existing biological process?  if so please
 describe*

#### Does this class require multiple inheritance classification?

*If yes please provide details/examples.*

#### Can we use design patterns & reasoning to populate subclasses?

*If yes, please provide details*

The `GO:molecular function regulator activity` branch already [has a design pattern](https://github.com/geneontology/design_patterns/blob/master/draft_patterns/activator_activity.yaml) and covers all classes here apart from GEF activity (which probably will be classified under this once we add a formal definitions) and this branch:

![image](https://cloud.githubusercontent.com/assets/112839/23117034/a230392e-f745-11e6-9c4c-ac6f48302454.png)

'signaling adaptor activity' could probably be accommodated elsewhere.  This is certainly protein-binding bridging.

The classification of regulator activities under `GO:molecular function regulator activity` will automatically mirror the classification of the regulated activities.

(Note: this ticket links to proposed work to fully implement the pattern: https://github.com/geneontology/go-ontology/issues/12995)

CC @thomaspd

**Comment by dosumis** [comment]
pattern for regulation via ... classes:

binding that directly_positively_regulates some fu
catalytic activity that directly_positively_regulates some bar

There should be lots of inference to these classes from LEGO.  Should we also be adding combinatorial subclasses e.g.  kinase activity regulator via binding.  Danger of combinatorial explosion here.

**Comment by pgaudet** [comment]
These terms have design pattern 'molecular_function and ('directly regulates' some molecular_function)' see 
https://github.com/geneontology/go-ontology/blob/master/src/design_patterns/regulator_activity.yaml
