### ISSUE TITLE
New top level MF class: Protein tagging activity

### ISSUE THREAD

**Issue by thomaspd** [geneontology/molecular_function_refactoring#47]
Definition: covalent protein modification activity that enables the target protein to be acted upon by another molecular function (e.g. ubiquitin-protein ligase, some kinases)

is a (catalytic activity has input proteinX) that regulates (molecular function enabled by protein Y has input protein X)

Children:
protein degradation tagging activity (protein tagging activity positively regulates some protein catabolic process)
tagging activity for cell surface protein internalization (protein tagging activity positively regulates some cell surface protein internalization process)

**Comment by pgaudet** [comment]
We can now do this better with GO-CAM.
