### ISSUE TITLE
Design pattern for compound MFs using NTPase as an energy source

### ISSUE THREAD

**Issue by dosumis** [geneontology/molecular_function_refactoring#48]
e.g motor proteins; ABC transporters.

It is important that the NTPase activity not be the genus.  Regulation of motor activity does not necessarily happen by regulating the NTPase activity driving it.

Example from 2017-02-28 annotation call LEGO model: classification of motor activity terms as subtypesof NTPase activity can lead to incorrect inferences around regulation.

present structure:

 GO:0017111 ! nucleoside-triphosphatase activity
 -- is_a GO:0003774 ! motor activity
 ---- is_a GO:0000146 ! microfilament motor activity
leads to inference

 regulation of nucleoside-triphosphatase activity
 -- is_a regulation of motor activity
 ---- is_a regulation of microfilament motor activity
but paper has a counter-example in which S.p. Rlc1 regulates motor activity of Myo2 (in complex with Cdc4 and Rlc1) but does not regulate Myo2 ATPase activity. Further details on call wiki http://wiki.geneontology.org/index.php/Annotation_Conf._Call_2017-02-28

**Comment by dosumis** [comment]
CC @mah11

**Comment by dosumis** [comment]
Potential pattern:

Simple version:

ATPase driven motor activity: EquivalentTo motor activity that has_part some 'ATPase activity'

But it would be better if we could indicate directly that the ATPase provides the power for the motor.  The only way to do this in the ontology is, as far as I can see, to invent a new subproperty of has_part (or perhaps of has_component).  has_energy_source?

**Comment by pgaudet** [comment]
This is covered by https://github.com/geneontology/go-ontology/issues/14012
