### ISSUE TITLE
TF activity term renaming - Paul T suggested scheme

### ISSUE THREAD

**Issue by dosumis** [geneontology/molecular_function_refactoring#5]
1. transcription factor activity, sequence-specific DNA binding -> transcription factor activity
   - Ditto subclasses
2. transcription factor activity, protein binding -> transcription regulator activity, protein binding
   - Ditto for all children apart from cofactors. e.g. transcription factor activity, RNA polymerase I binding -> transcription regulator activity, RNA polymerase I transcription factor binding.
   - The defs of all terms in the branch that are not under co-factor have the clause "may or may not also interact with the template nucleic acid." So cofactor remains a subclass.

@thomaspd

**Comment by dosumis** [comment]
@thomaspd : Remaining question, what to do with 'nucleic acid binding ...'  & 'RNA binding...' TF terms:

![image](https://cloud.githubusercontent.com/assets/112839/11901407/5b3acab0-a5a3-11e5-91d8-33df75b8125a.png)

Are there any other RNA binding TF activities besides anti-termination factor?  Check ref: PMID:8332211 
What direct annotations to this are there to this?

Could move anti-termination to be regulator.

**Comment by dosumis** [comment]
Progress:

Generated a [Mapping table](https://github.com/geneontology/molecular_function_refactoring/blob/master/TF_activity_renaming_spec/mapping.tsv).  This needs to be reviewed.
- For descendant classes of 'transcription factor activity, sequence-specific DNA binding', I have only shortened the name if the second half after the comma is the string 'sequence-specific DNA binding'
- For descendant classes  of 'transcription factor activity, protein binding' I have changed all 'transcription factor activity,...' TO 'transcription regulator activity...'. 
  - In this branch, please pay attention to whether the name change is justified in both branches under 'transcription factor activity, protein binding': 
    ![image](https://cloud.githubusercontent.com/assets/112839/11902244/50cd8180-a5a8-11e5-93c8-1de30d22848a.png)

**Comment by dosumis** [comment]
Note: Keep current names as synonyms.

**Comment by dosumis** [comment]
Notes on mapping table what's changed and what's not: 

Only the upper level terms in the DNA binding branch are specified for change:

'transcription factor activity, sequence-specific DNA binding'
'bacterial-type RNA polymerase transcription factor activity, sequence-specific DNA binding'
'bacterial-type RNA polymerase transcriptional activator activity, sequence-specific DNA binding'
'bacterial-type RNA polymerase transcriptional repressor activity, sequence-specific DNA binding'
'mitochondrial RNA polymerase transcription factor activity, sequence-specific DNA binding'
'RNA polymerase I transcription factor activity, sequence-specific DNA binding'
'RNA polymerase II transcription factor activity, sequence-specific DNA binding'
'RNA polymerase III transcription factor activity, sequence-specific DNA binding'
'RNA polymerase II transcription factor activity, sequence-specific transcription regulatory region DNA binding'
'RNA polymerase II transcription factor activity, TBP-class protein binding'
'RNA polymerase II transcription factor activity, TBP-class protein binding, involved in preinitiation complex assembly'
'RNA polymerase III hybrid type promoter TFIIIB recruiting transcription factor activity'
'RNA polymerase III hybrid type promoter TFIIIB-type transcription factor activity'
'RNA polymerase III type 1 promoter TFIIIB-type transcription factor activity'
'RNA polymerase III type 2 promoter TFIIIB-type transcription factor activity'
'RNA polymerase III type 3 promoter TFIIIB-type transcription factor activity'v
'RNA polymerase I transcription factor activity, sequence-specific DNA binding'
'RNA polymerase II transcription factor activity, sequence-specific DNA binding'
'RNA polymerase III transcription factor activity, sequence-specific DNA binding'

Where the DNA binding activity is more specific or there is some additional regulator mechanism or binding some co-factor is specified.  The old names have been kept.  e.g.

'RNA polymerase II transcription factor activity, copper ion regulated core promoter proximal region sequence-specific binding'
'RNA polymerase II transcription factor activity, estrogen-activated sequence-specific DNA binding'
'transcription factor activity, RNA polymerase III promoter sequence-specific binding, TFIIIB recruiting'

There is probably more scope for improvement here.
Transcriptional activator and repressor terms have also been left untouched.

On the TF activity, protein binding side there are 62 terms.  Only 33 are specified to change.  Those not specified to change include 10 classes under both branches:

'RNA polymerase II transcription factor activity, sequence-specific transcription regulatory region DNA binding'
'RNA polymerase III hybrid type promoter TFIIIB recruiting transcription factor activity'
'transcription factor activity, RNA polymerase I CORE element binding transcription factor recruiting'
'transcription factor activity, RNA polymerase III promoter sequence-specific binding, TFIIIB recruiting'
'transcription factor activity, RNA polymerase III type 1 promoter sequence-specific binding, TFIIIB recruiting'
'transcription factor activity, RNA polymerase III type 1 promoter sequence-specific binding, TFIIIC recruiting'
'transcription factor activity, RNA polymerase III type 2 promoter sequence-specific binding, TFIIIB recruiting'
'transcription factor activity, RNA polymerase III type 3 promoter TFIIIB recruiting'
'transcription factor activity, sequence-specific DNA binding transcription factor recruiting'

AND:

'RNA polymerase II transcription coactivator activity involved in preinitiation complex assembly'
'RNA polymerase II transcription coactivator activity'
'RNA polymerase II transcription cofactor activity'
'RNA polymerase II transcription corepressor activity'
'RNA polymerase II transcription factor activity, TBP-class protein binding'
'RNA polymerase II transcription factor activity, TBP-class protein binding, involved in preinitiation complex assembly'
'RNA polymerase III hybrid type promoter TFIIIB-type transcription factor activity'
'RNA polymerase III type 1 promoter TFIIIB-type transcription factor activity'
'RNA polymerase III type 2 promoter TFIIIB-type transcription factor activity'
'RNA polymerase III type 3 promoter TFIIIB-type transcription factor activity'
'TFIIIB-type transcription factor activity'
'anti-sigma factor antagonist activity'
'core DNA-dependent RNA polymerase binding promoter specificity activity'
'glucocorticoid-activated RNA polymerase II transcription factor binding transcription factor activity'
'ligand-dependent nuclear receptor transcription coactivator activity'
'mitochondrial RNA polymerase binding promoter specificity activity'
'plastid sigma factor activity'
'sigma factor activity'
'sigma factor antagonist activity'
'thyroid hormone receptor coactivator activity'
'transcription coactivator activity'
'transcription cofactor activity'
'transcription corepressor activity'
'transcription factor activity, protein binding'
'transcriptional activator activity, RNA polymerase II transcription factor binding'
'transcriptional repressor activity, RNA polymerase II activating transcription factor binding'
'transcriptional repressor activity, RNA polymerase II transcription factor binding'

**Comment by dosumis** [comment]
- [ ] @rlovering to review

**Comment by krchristie** [comment]
I think it would be really unfortunate to reinstate a problem we already fixed where people see "transcription factor activity" and use it for any kind of transcription factor, even ones that don't bind DNA. No matter how much you say that people are supposed to annotate to the definition, you know that they often do not bother to read it; they just the name.

transcription factor activity, sequence-specific DNA binding -> transcription factor activity

**Comment by pgaudet** [comment]
These terms were updated in the Transcription factor overhaul 2018 project - https://github.com/geneontology/go-ontology/projects/7
