### ISSUE TITLE
TF refactoring umbrella ticket

### ISSUE THREAD

**Issue by dosumis** [geneontology/molecular_function_refactoring#50]
An umbrella ticket (epic) for finishing TF refactoring.

Overview:

   This will be considered completed when: 
      - Pattern finally agreed  - I currently have one that works, but some dispute over how this fits with desired patterns for combinatorial action (e.g. recording boolean logic of promoters.
      - A branch with edits is in place and ready to merge
         - textual component edit is taking shape in Spreadsheet tsv.  This can be implemented with perl script (in placer) or via DOSDP-tools.
         - logical component - via dosdp with label/def over-ride.
      - a complete writeup is in place.

**Comment by pgaudet** [comment]
Done here: 
https://github.com/geneontology/go-ontology/projects/7
