### ISSUE TITLE
Consider obsoleting molecular transducer activity

### ISSUE THREAD

**Issue by dosumis** [geneontology/molecular_function_refactoring#7]
It is currently very vaguely defined:

"The molecular function that accepts an input of one form and creates an output of a different form."

Doesn't this apply to anything with enzyme activity?  Guess it depends on what is meant by form.

Should either be obsoleted or more tightly defined.

@thomaspd

**Comment by thomaspd** [comment]
I thought we agreed to define it more tightly, as a compound molecular function that has at least one sensing activity, and an effector activity. It detects a molecular-level interaction, and transduces that interaction by changing another one of its own activities.

**Comment by dosumis** [comment]
> I thought we agreed to define it more tightly,

We did.  I should have added a note when closing to say that this ticket has been superseded by #31
